import './globals.css'
import React from "react";

export const metadata = {
  title: 'Next.js Scholarship App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-background">{children}</body>
    </html>
  )
}
